<?php

namespace App\Services\YouTube;

use App\Models\Listing;
use Illuminate\Support\Str;

/**
 * Builds the YouTube title / description / tags for a listing video from the
 * listing's own fields — every video's metadata is unique to its property
 * (title, price, specs, location, canonical URL), which is exactly what keeps
 * an automated channel on the right side of YouTube's spam policies.
 *
 * Links deliberately use the CANONICAL listing URL (not a shortener): YouTube
 * description links are nofollow either way, so the value is brand/entity
 * consistency and honest click-through, not equity.
 */
class ListingVideoMetadata
{
    public function __construct(private Listing $listing)
    {
    }

    /** "{name} — {category} in {City}, {Province}" clamped to YouTube's 100 chars. */
    public function title(): string
    {
        $l = $this->listing;
        $location = $this->shortLocation();

        $title = trim($l->name);
        $suffix = ' — ' . ($l->category?->name ?? 'For Sale') . ($location ? " in {$location}" : '');

        // Prefer trimming the property name over losing the searchable
        // "{category} in {location}" tail — that tail IS the long-tail query.
        $max = 100;
        if (mb_strlen($title . $suffix) > $max) {
            $title = mb_substr($title, 0, max(10, $max - mb_strlen($suffix) - 1)) . '…';
        }

        return $title . $suffix;
    }

    /**
     * Append GA attribution params (OnePropertee-style, minus the URL
     * shortener — a visible filipinohomes.com link is itself a trust cue).
     * utm_campaign = the listing code (known BEFORE upload, human-readable in
     * analytics); utm_content distinguishes which description link was clicked.
     * Self-referencing canonicals on our pages make the UTM'd URLs SEO-inert.
     */
    private function utm(string $url, string $content): string
    {
        $sep = str_contains($url, '?') ? '&' : '?';

        return $url . $sep . http_build_query([
            'utm_source' => 'youtube',
            'utm_medium' => 'autogenerated',
            'utm_campaign' => $this->listing->code ?: ('listing-' . $this->listing->id),
            'utm_content' => $content,
        ]);
    }

    /**
     * Matching typed hub page ("/for-sale/house/in-cebu-city-cebu") — funnels
     * video viewers into our programmatic SEO pages, mirroring OnePropertee's
     * category-link line. Mirrors buildRelatedSearchLink's URL convention on
     * the frontend (/{category}/{type}/in-{city}-{province}); null when the
     * listing lacks registry city/province or a type (no link beats a 404).
     *
     * @return array{label: string, url: string}|null
     */
    private function hubLink(): ?array
    {
        $l = $this->listing;
        $city = $l->property?->barangay?->city?->name;
        $province = $l->property?->barangay?->city?->province?->name;
        $type = $l->property?->propertyAttribute?->subtype?->type?->name;
        $categoryPath = match (strtolower($l->category?->name ?? '')) {
            'for sale' => 'for-sale',
            'for rent' => 'for-rent',
            default => null,
        };
        if (!$city || !$province || !$type || !$categoryPath) {
            return null;
        }

        $site = rtrim(config('services.youtube.site_url', 'https://filipinohomes.com'), '/');
        $locSlug = Str::slug($city) . '-' . Str::slug($province);

        return [
            'label' => "{$type} {$l->category->name} in {$city}, {$province}",
            'url' => "{$site}/{$categoryPath}/" . Str::slug($type) . "/in-{$locSlug}",
        ];
    }

    public function description(): string
    {
        $l = $this->listing;
        $attr = $l->property?->propertyAttribute;
        $site = rtrim(config('services.youtube.site_url', 'https://filipinohomes.com'), '/');
        $listingUrl = $site . '/' . $l->slug;

        $specBits = array_filter([
            $l->price > 0 ? '₱' . number_format((float) $l->price) : null,
            $attr?->bedroom_count ? ((int) $attr->bedroom_count) . ' Bed' : null,
            $attr?->bathroom_count ? ((int) $attr->bathroom_count) . ' Bath' : null,
            (float) ($attr?->floor_area ?? 0) > 0 ? number_format((float) $attr->floor_area) . ' sqm floor' : null,
            (float) ($attr?->lot_area ?? 0) > 0 ? number_format((float) $attr->lot_area) . ' sqm lot' : null,
        ]);

        $agent = $l->agent;
        $agentLine = null;
        if ($agent) {
            $agentName = trim(($agent->first_name ?? '') . ' ' . ($agent->last_name ?? ''));
            $agentSlug = Str::slug($agentName);
            $agentUrl = $site . '/agents/' . ($agentSlug ? $agentSlug . '-' : '') . $agent->id;
            $agentLine = "Listed by {$agentName} — contact the agent: " . $this->utm($agentUrl, 'agent');
        }

        // Hub line — anchor text is the destination page's target query.
        $hub = $this->hubLink();
        $hubLine = $hub ? "{$hub['label']}: " . $this->utm($hub['url'], 'hub') : null;

        // Plain-text excerpt of the listing description (strip tags/entities,
        // clamp) so each video body is unique beyond the templated lines.
        $excerpt = trim(html_entity_decode(strip_tags((string) ($l->property?->description ?? ''))));
        $excerpt = $excerpt !== '' ? Str::limit(preg_replace('/\s+/', ' ', $excerpt), 500) : null;

        $lines = array_filter([
            $l->name . ' — ' . ($l->category?->name ?? 'For Sale') . ' in ' . ($l->property?->address ?? $this->shortLocation()),
            $specBits ? implode(' · ', $specBits) : null,
            '',
            'View this property: ' . $this->utm($listingUrl, 'listing'),
            $agentLine,
            $hubLine,
            '',
            $excerpt,
            '',
            implode(' ', $this->hashtags()),
        ], fn ($line) => $line !== null);

        // 5000-byte API ceiling.
        return mb_strcut(implode("\n", $lines), 0, 4900);
    }

    /** @return string[] */
    public function tags(): array
    {
        $l = $this->listing;
        $city = $l->property?->barangay?->city?->name;
        $province = $l->property?->barangay?->city?->province?->name;
        $type = $l->property?->propertyAttribute?->subtype?->type?->name;
        $cat = strtolower($l->category?->name ?? 'for sale');

        return array_values(array_filter(array_unique([
            'Filipino Homes',
            'Philippines real estate',
            $type ? "{$type} {$cat}" : null,
            $city ? "{$type} {$cat} in {$city}" : null,
            $city,
            $province,
            $city && $province ? "{$city} {$province} properties" : null,
        ])));
    }

    /** @return string[] */
    public function hashtags(): array
    {
        $l = $this->listing;
        $city = $l->property?->barangay?->city?->name;
        $type = $l->property?->propertyAttribute?->subtype?->type?->name;

        $camel = fn (?string $s) => $s ? str_replace(' ', '', ucwords(preg_replace('/[^A-Za-z0-9 ]/', '', $s))) : null;

        return array_values(array_filter([
            '#FilipinoHomes',
            $camel($city) ? '#' . $camel($city) . 'Properties' : null,
            $camel($type) && $camel($city)
                ? '#' . $camel($type) . 'ForSaleIn' . $camel($city)
                : null,
        ]));
    }

    private function shortLocation(): string
    {
        $city = $this->listing->property?->barangay?->city?->name;
        $province = $this->listing->property?->barangay?->city?->province?->name;

        return implode(', ', array_filter([$city, $province !== $city ? $province : null]));
    }

    /**
     * Auto-generated SRT caption track. The slideshow has no speech, so this
     * IS the transcript — and caption text is indexed by YouTube search,
     * giving the keyword phrases ("{type} for sale in {city}") a surface the
     * music-only video otherwise lacks. Mirrors OnePropertee's visible
     * "Contact seller through the link in the description" closing caption.
     *
     * Cues track the video structure: intro card → photo run (split in two)
     * → end card. $totalSeconds comes from the composer's computed duration.
     */
    public function captionSrt(float $totalSeconds): string
    {
        $l = $this->listing;
        $attr = $l->property?->propertyAttribute;

        $specBits = array_filter([
            $l->price > 0 ? '₱' . number_format((float) $l->price) : null,
            $attr?->bedroom_count ? ((int) $attr->bedroom_count) . ' Bedroom' . ((int) $attr->bedroom_count > 1 ? 's' : '') : null,
            $attr?->bathroom_count ? ((int) $attr->bathroom_count) . ' Bathroom' . ((int) $attr->bathroom_count > 1 ? 's' : '') : null,
            (float) ($attr?->floor_area ?? 0) > 0 ? number_format((float) $attr->floor_area) . ' sqm' : null,
        ]);

        $introEnd = min(2.5, $totalSeconds / 4);
        $outroStart = max($introEnd + 1, $totalSeconds - 4.0);
        $midpoint = $introEnd + ($outroStart - $introEnd) / 2;

        $cues = [
            [0.0, $introEnd, $l->name . ' — ' . ($l->category?->name ?? 'For Sale') . ' in ' . $this->shortLocation()],
            [$introEnd, $midpoint, $specBits ? implode(' · ', $specBits) : $l->name],
            [$midpoint, $outroStart, 'Located in ' . ($l->property?->address ?? $this->shortLocation())],
            [$outroStart, $totalSeconds, 'Contact the agent through the link in the description'],
        ];

        $srt = [];
        foreach ($cues as $i => [$from, $to, $text]) {
            if ($to <= $from || trim((string) $text) === '') {
                continue;
            }
            $srt[] = ($i + 1) . "\n"
                . self::srtTime($from) . ' --> ' . self::srtTime($to) . "\n"
                . trim($text);
        }

        return implode("\n\n", $srt) . "\n";
    }

    private static function srtTime(float $seconds): string
    {
        $ms = (int) round(($seconds - floor($seconds)) * 1000);
        $s = (int) floor($seconds);

        return sprintf('%02d:%02d:%02d,%03d', intdiv($s, 3600), intdiv($s % 3600, 60), $s % 60, $ms);
    }
}
